### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by mauritsunkel** [multichannelsystems/McsPyDataTools#2]
Hi MCS!, 

I've been trying to follow the tutorial at https://mcspydatatools.readthedocs.io/en/latest/McsPy-Tutorial_DataAnalysis.html with ipython from a local jupyter notebook after setting your testData files in advised structure.

After running cell 5 (plot_analog_stream_channel(electrode_stream, 0, from_in_s=0, to_in_s=500)) I receive the following error:

===============================================================
ValueError                                Traceback (most recent call last)
<ipython-input-30-6785d4a95fc8> in <module>
----> 1 plot_analog_stream_channel(electrode_stream, 0, from_in_s=0, to_in_s=500)

<ipython-input-29-65988a667310> in plot_analog_stream_channel(analog_stream, channel_idx, from_in_s, to_in_s, show)
     38     # construct the plot
     39     _ = plt.figure(figsize=(20,6))
---> 40     _ = plt.plot(np.array(time_in_sec), np.array(signal_in_uV))
     41     _ = plt.xlabel('Time (%s)' % ureg.s)
     42     _ = plt.ylabel('Voltage (%s)' % ureg.uV)

E:\Software\Anaconda3_2020.02_64x\lib\site-packages\matplotlib\pyplot.py in plot(scalex, scaley, data, *args, **kwargs)
   2794     return gca().plot(
   2795         *args, scalex=scalex, scaley=scaley, **({"data": data} if data
-> 2796         is not None else {}), **kwargs)
   2797 
   2798 

E:\Software\Anaconda3_2020.02_64x\lib\site-packages\matplotlib\axes\_axes.py in plot(self, scalex, scaley, data, *args, **kwargs)
   1663         """
   1664         kwargs = cbook.normalize_kwargs(kwargs, mlines.Line2D._alias_map)
-> 1665         lines = [*self._get_lines(*args, data=data, **kwargs)]
   1666         for line in lines:
   1667             self.add_line(line)

E:\Software\Anaconda3_2020.02_64x\lib\site-packages\matplotlib\axes\_base.py in __call__(self, *args, **kwargs)
    223                 this += args[0],
    224                 args = args[1:]
--> 225             yield from self._plot_args(this, kwargs)
    226 
    227     def get_next_color(self):

E:\Software\Anaconda3_2020.02_64x\lib\site-packages\matplotlib\axes\_base.py in _plot_args(self, tup, kwargs)
    389             x, y = index_of(tup[-1])
    390 
--> 391         x, y = self._xy_from_xy(x, y)
    392 
    393         if self.command == 'plot':

E:\Software\Anaconda3_2020.02_64x\lib\site-packages\matplotlib\axes\_base.py in _xy_from_xy(self, x, y)
    268         if x.shape[0] != y.shape[0]:
    269             raise ValueError("x and y must have same first dimension, but "
--> 270                              "have shapes {} and {}".format(x.shape, y.shape))
    271         if x.ndim > 2 or y.ndim > 2:
    272             raise ValueError("x and y can be no greater than 2-D, but have "

ValueError: x and y must have same first dimension, but have shapes (12500002,) and (12500001,)
===============================================================

I was hoping to gain an understanding of the data structure through the tutorial, I hope you can help me with fixing this error.

Regards,
Maurits

**Comment by armwal** [comment]
Hi Maurits,

thanks for reporting this error! This seems to be a bug in the `get_channel_sample_timestamps()` function which outputs an array of the wrong shape if an end index is given. We'll fix this shortly!

For the moment, you could simply remove the `to_in_s` parameter in cell 5 and instead call

`plot_analog_stream_channel(electrode_stream, 0, from_in_s=0)`

Best,
Armin

**Comment by mauritsunkel** [comment]
Hi Armin,

Thanks for the quick reply, I look forward to the fixed tutorial and will continue withholding the parameter.

**Comment by armwal** [comment]
Hi Maurits,

we've released version 0.4.1 of the McsPyDataTools which contains the bug fix for the `get_channel_sample_timestamps()` function. Please update to the newest version of the package and you should be able to run the tutorial.

Thanks again for the bug report!
Armin
