### ISSUE TITLE
Mc_rack

### ISSUE THREAD

**Issue by RRaphaell** [multichannelsystems/McsPyDataTools#3]
My team and I found out such inaccuracies when processing the files. We have analyzed spikes both from the Mc_rack app and McsPy-Tutorial_DataAnalysis.ipynb.
I have exported spikes from Mc_Rack and also launched a notebook with the same parameters but the number of spikes did not match. 
For example, the quantity of the spikes exported from Mc_Rack was 9370 and the quantity of the spikes in the notebook at the same channel was 8948. Could you please help me clarify why such a thing happens? Does Mc_Rack use a different algorithm, unlike this notebook?

**Comment by armwal** [comment]
Hi,

correct, the spike detection algorithm in MC_Rack works differently than the one in the Tutorial_DataAnalysis notebook. In the notebook, the spike detection threshold is determined using the MAD estimator on the whole data, whereas MC_Rack uses the standard deviation of the first 500 ms of data to determine the threshold (see section 4.13.2 in the MC_Rack manual). So the spike detection thresholds will differ between the two, leading to different spike counts. 

The spike detection method in the notebook is mainly intended for illustrative purposes.

Best,
Armin

**Comment by RRaphaell** [comment]
Thank you very much.
I forgot to say that I used -120 micro walts as a threshold at MC Rack and I've used the same threshold in this notebooks too. I mean, I've commented those MAD estimator parts in notebook and used my threshold instead
`# spike_threshold = -5 * noise_mad # roughly -30 µV`
`spike_threshold = -0.00012`

**Comment by armwal** [comment]
Thanks for the information! Has the **Dead Time** been set to the same value as well for MC_Rack and the Notebook?

**Comment by RRaphaell** [comment]
yes 2 ms in both

**Comment by armwal** [comment]
OK, thanks. Could you send us screenshots of the spike detection parameters you set in MC_Rack and the recording as an .mcd file? We'll try to replicate the issue here. Please also let us know which channel you've used for the test.

**Comment by RRaphaell** [comment]
Here is the link where I uploaded the .mcd file (The notebook reads the .h5 file, I used Multi Channel DataManager for conversion) and the screenshots as well. Channel ID is 47 (label 0)
https://drive.google.com/drive/folders/1lpdU2dMwIDUZDTTgvAz6NQHnGCGDYadh?usp=sharing

**Comment by armwal** [comment]
Thanks for providing the data! I've had a look at the exact implementation, and here is a modified version of the `detect_threshold_crossings` function in the notebook which should replicate the MC_Rack spike detection:

```python
def detect_threshold_crossings(signal, fs, threshold, dead_time):
    """
    Detect threshold crossings in a signal with dead time and return them as an array
    
    The signal transitions from a sample above the threshold to a sample below the threshold for a detection and
    the last detection has to be more than dead_time apart from the current one.
    
    :param signal: The signal as a 1-dimensional numpy array
    :param fs: The sampling frequency in Hz
    :param threshold: The threshold for the signal
    :param dead_time: The dead time in seconds. 
    """
    dead_time_idx = dead_time * fs
    last_idx = -dead_time_idx
    threshold_crossings = []
    for idx in range(len(signal)):
        if idx > 0 and signal[idx-1] > threshold and signal[idx] <= threshold and idx - last_idx > dead_time_idx + 1:
            threshold_crossings.append(idx)
            last_idx = idx
    return threshold_crossings
```

The previous implementation in the notebook may have been faster, but skipped some spikes. As we noted at the start of the notebook: It is not intended to provide production-grade algorithms but should serve as an introduction into the topic.

**Comment by RRaphaell** [comment]
Thank you very much, now it works.
I also have one question, It’s about the burst detection algorithm.
Here’s my implementation of burst detection algorithm based on Mc_rack_manual.pdf pseudo code (I’m attaching pseudo-code screen below) and my implementation of bursts in almost all channels returns more bursts than does Mc_rack. 
(for example: for the 45th channel, my code returns 18 bursts while Mc_rack does 16).
It would be really helpful for me if you could provide any help for this issue too. 
Thanks in advance for everything. I really appreciate your help


![asd](https://drive.google.com/uc?export=view&id=1DIi6FjVIbuxrTLfzdEc_7ag1HB_ORXPx)

      spikes_in_s = spks/fs
      max_interval_to_start_burst = 10/1000
      max_interval_to_end_burst = 10/1000
      min_interval_between_bursts = 10/1000
      min_duration_of_burst = 20/1000
      min_number_of_spikes = 4
      
      all_burst = []
      i = 0
      while i < len(spikes_in_s)-1:
          if (spikes_in_s[i+1]-spikes_in_s[i]) <= max_interval_to_start_burst:
              burst_start_in_s = spikes_in_s[i]
              while (i < len(spikes_in_s)-1) and ((spikes_in_s[i+1]-spikes_in_s[i]) < max_interval_to_end_burst):
                  i += 1
              burst_end_in_s = spikes_in_s[i]   
              all_burst.append((burst_start_in_s, burst_end_in_s))
          else:
              i+=1
      # merg bursts        
      merged_bursts=[]
      temp_burst = all_burst[0]
      for i in range(1, len(all_burst)):
          if (all_burst[i][0] - temp_burst[1]) < min_interval_between_bursts:
              temp_burst[1] = all_burst[i][1]
          else:
              merged_bursts.append(temp_burst)
              temp_burst = all_burst[i]      
      # filter bursts
      quantity = 0
      for burst in merged_bursts:
          num_spike_in_burst = len(spikes_in_s[(spikes_in_s>=burst[0]) & (spikes_in_s<=burst[1])])
          if (((burst[1]-burst[0]) >= min_duration_of_burst) and (num_spike_in_burst >= min_number_of_spikes)):
              quantity += 1

**Comment by armwal** [comment]
I had a look at the MC_Rack code, and my suspicion is that the description in the manual doesn't exactly match the behaviour of MC_Rack. The Merge step seems to happen in MC_Rack after the step where the number of spikes and the duration is checked, so only valid bursts that fulfill all criteria are merged together. 

This is probably a bug, but MC_Rack has been deprecated for more than 6 years and was superseded by the Multi Channel Experimenter/Analyzer software which implements the burst detection as stated in the manual. Because of this, we don't release bug fixes anymore for MC_Rack and unfortunately won't be able to do an in-depth analysis of this issue.
