### ISSUE TITLE
.get_channel_in_range is very slow

### ISSUE THREAD

**Issue by RRaphaell** [multichannelsystems/McsPyDataTools#4]
I have a signal record that is about 900 seconds long and the get_channel_in_range needs 14 seconds to read
any help? how can I make it faster

**Comment by armwal** [comment]
Hi Raphael,
I ran a quick test with a file that is about 600 seconds long (recorded with 20 kHz, so there are 12000000 samples per channel), and `get_channel_in_range` took less than 5 seconds to read and return the data. Basically all of this time is spent by the underlying h5py library to read the data from the HDF5 file. 

Is the HDF5 file you are reading from located on an SSD? A HDD? Or on a network drive? This would make a massive difference, having the file on an SSD would of course be the fastest option.

Armin

**Comment by RRaphaell** [comment]
thanks for your answer, which other formats ( not hdf5) can we use for better performance?

**Comment by armwal** [comment]
If you are reading the file from an SSD, I'm surprised that it takes 14 seconds... What sampling rate was used during the recording? 

Honestly, I'm not sure if you would be getting much faster results with other file formats. There are a few things you could try, however:
- The HDF5 files are compressed by default. This gives you smaller file sizes but it obviously adds some overhead when it comes to reading the data. You could try to deactivate compression in the Multi Channel DataManager in the File -> Export Settings menu.
- You could try using the ASCII export in the Multi Channel DataManager, but I except that the resulting files will be huge given your long recordings
- You could access the data in the file directly via the `h5py` library. This gives you an idea how long the actual reading of the data from the HDF5 file takes. If this also takes about 14 seconds, there isn't much we can to, unfortunately. If it is faster, it might be a bug in the McsPyDataTools which we should investigate. Here is a very simplified example:

```python
import h5py
f = h5py.File(YOUR_FILE_NAME.h5)
data = f['/Data/Recording_0/AnalogStream/Stream_0/ChannelData'][0,:] # this reads all the samples for the first channel in the first analog stream of the file
```

**Comment by RRaphaell** [comment]
I have a 25kH sampling frequency. thanks, I will try all the possible solutions which you wrote

**Comment by RRaphaell** [comment]
> If you are reading the file from an SSD, I'm surprised that it takes 14 seconds... What sampling rate was used during the recording?
> 
> Honestly, I'm not sure if you would be getting much faster results with other file formats. There are a few things you could try, however:
> 
> * The HDF5 files are compressed by default. This gives you smaller file sizes but it obviously adds some overhead when it comes to reading the data. You could try to deactivate compression in the Multi Channel DataManager in the File -> Export Settings menu.
> * You could try using the ASCII export in the Multi Channel DataManager, but I except that the resulting files will be huge given your long recordings
> * You could access the data in the file directly via the `h5py` library. This gives you an idea how long the actual reading of the data from the HDF5 file takes. If this also takes about 14 seconds, there isn't much we can to, unfortunately. If it is faster, it might be a bug in the McsPyDataTools which we should investigate. Here is a very simplified example:
> 
> ```python
> import h5py
> f = h5py.File(YOUR_FILE_NAME.h5)
> data = f['/Data/Recording_0/AnalogStream/Stream_0/ChannelData'][0,:] # this reads all the samples for the first channel in the first analog stream of the file
> ```

thanks, I've converted files without compression and it took only a few seconds but the size was 5 times larger
